### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by zzwei1** [maahn/pamtra2#6]
I have installed the required python packages:
numpy
scipy
xarray
json
dask
numba
cython
When I use python setup.py install,I got the following errors:
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'build_requires'
  warnings.warn(msg)
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'build_requires'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "pamtra2.libs.pamgasabs.pamgasabs_lib" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib' to include_dirs.
Reading .f2py_f2cmap ...
	Mapping "real(kind=dbl)" to "double"
	Mapping "real(kind=sgl)" to "float"
	Mapping "complex(kind=dbl)" to "complex_double"
	Mapping "complex(kind=sgl)" to "complex_float"
	Mapping "integer(kind=long)" to "int"
	Mapping "integer(kind=long_bn)" to "int"
Successfully applied user defined changes from .f2py_f2cmap
  adding 'build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_lib-f2pywrappers2.f90' to sources.
building extension "pamtra2.libs.pyPamtraRadarSimulator.pyPamtraRadarSimulatorLib" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pyPamtraRadarSimulator/pyPamtraRadarSimulator/pyPamtraRadarSimulatorLib/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pyPamtraRadarSimulator/pyPamtraRadarSimulator/pyPamtraRadarSimulatorLib' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/libs/pyPamtraRadarSimulator/pyPamtraRadarSimulator/pyPamtraRadarSimulatorLib/pyPamtraRadarSimulatorLib-f2pywrappers2.f90' to sources.
building extension "pamtra2.libs.pyPamtraRadarMoments.pyPamtraRadarMomentsLib" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pyPamtraRadarMoments/pyPamtraRadarMoments/pyPamtraRadarMomentsLib/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pyPamtraRadarMoments/pyPamtraRadarMoments/pyPamtraRadarMomentsLib' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/libs/pyPamtraRadarMoments/pyPamtraRadarMoments/pyPamtraRadarMomentsLib/pyPamtraRadarMomentsLib-f2pywrappers2.f90' to sources.
building extension "pamtra2.libs.singleScattering.cMie" sources
building extension "pamtra2.libs.singleScattering.fTMat" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/singleScattering/Tmatrix/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/singleScattering/Tmatrix' to include_dirs.
build_src: building npy-pkg config files
writing pamtra2.egg-info/PKG-INFO
writing dependency_links to pamtra2.egg-info/dependency_links.txt
writing requirements to pamtra2.egg-info/requires.txt
writing top-level names to pamtra2.egg-info/top_level.txt
reading manifest file 'pamtra2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
**no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'doc/generated'
warning: no previously-included files matching '.DS_Store' found anywhere in distribution**
writing manifest file 'pamtra2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:517: UserWarning: FFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  fflags = self.flag_vars.flags + dflags + oflags + aflags
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:530: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_so_flags = self.flag_vars.linker_so
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:540: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_exe_flags = self.flag_vars.linker_exe
customize Gnu95FCompiler
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:517: UserWarning: FFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  fflags = self.flag_vars.flags + dflags + oflags + aflags
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:530: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_so_flags = self.flag_vars.linker_so
/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:540: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_exe_flags = self.flag_vars.linker_exe
customize Gnu95FCompiler using build_ext
building 'pamtra2.libs.pamgasabs.pamgasabs_lib' extension
compiling C sources
C compiler: gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/zzwei/Build_WRF/LIBRARIES/grib2/include -fPIC

compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib -I/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/core/include -I/home/zzwei/anaconda2/envs/wradlib/include/python3.7m -c'
compiling Fortran 90 module sources
Fortran f77 compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -O3 -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -O3 -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -O3 -O3 -funroll-loops
compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib -I/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/core/include -I/home/zzwei/anaconda2/envs/wradlib/include/python3.7m -c'
extra options: '-Jbuild/temp.linux-x86_64-3.7/pamtra2/libs/pamgasabs -Ibuild/temp.linux-x86_64-3.7/pamtra2/libs/pamgasabs'
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/kinds.f90
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/report_module.f90
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/constants.f90
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/gasabs_module.f90
compiling Fortran sources
Fortran f77 compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -O3 -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -O3 -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -O3 -O3 -funroll-loops
compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib -I/home/zzwei/anaconda2/envs/wradlib/lib/python3.7/site-packages/numpy/core/include -I/home/zzwei/anaconda2/envs/wradlib/include/python3.7m -c'
extra options: '-Jbuild/temp.linux-x86_64-3.7/pamtra2/libs/pamgasabs -Ibuild/temp.linux-x86_64-3.7/pamtra2/libs/pamgasabs'
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/rosen98_gasabs.f90
gfortran:f90: libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:341:13:

   ZN = CMPLX(0._dbl, 0._dbl)
             1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:349:36:

       - CMPLX(1._dbl,DELTA) / CMPLX(F0O2(I) + freq,GAMMA))
                                    1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:349:14:

       - CMPLX(1._dbl,DELTA) / CMPLX(F0O2(I) + freq,GAMMA))
              1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:348:58:

      ZF = freq / F0O2(I) * (CMPLX (1._dbl,-DELTA) / CMPLX(F0O2(I) - freq,-GAMMA
                                                          1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:348:35:

      ZF = freq / F0O2(I) * (CMPLX (1._dbl,-DELTA) / CMPLX(F0O2(I) - freq,-GAMMA
                                   1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:359:13:

   ZN = CMPLX(0._dbl,0._dbl)
             1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:362:22:

   ZFo = -freq / CMPLX(freq,GAMMAo)
                      1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:364:17:

   ZFn = CMPLX(0.,freq / (1.93d-5 * freq**1.5 + 1._dbl) )
                 1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:371:13:

   ZN = CMPLX(0._dbl,0._dbl)
             1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:381:34:

      - CMPLX(1._dbl,DELH) / CMPLX(F0H2O(I) + freq,GAMH))
                                  1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:381:13:

      - CMPLX(1._dbl,DELH) / CMPLX(F0H2O(I) + freq,GAMH))
             1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:380:58:

      ZF = freq / F0H2O(I) * (CMPLX(1._dbl, -DELH) / CMPLX(F0H2O(I) - freq, -GAM
                                                          1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:380:35:

      ZF = freq / F0H2O(I) * (CMPLX(1._dbl, -DELH) / CMPLX(F0H2O(I) - freq, -GAM
                                   1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:402:26:

           - Eopt) / CMPLX(freq,fS))
                          1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:401:47:

      ZEp = Eps - freq * ((Eps - Epinf) / CMPLX(freq, fD) + (Epinf &
                                               1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.f90:412:17:

      ZEp = CMPLX(3.15_dbl,Ai / fice+Bi * fice)
                 1
Warning: Conversion from REAL(8) to default-kind COMPLEX(4) at (1) might lose precision, consider using the KIND argument [-Wconversion]
gfortran:f90: build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_lib-f2pywrappers2.f90
/usr/bin/gfortran -Wall -g -L/home/zzwei/Build_WRF/LIBRARIES/grib2/lib -shared build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_libmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/fortranobject.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/kinds.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/report_module.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/constants.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/gasabs_module.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/rosen98_gasabs.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_lib-f2pywrappers2.o -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -lgfortran -o build/lib.linux-x86_64-3.7/pamtra2/libs/pamgasabs/pamgasabs_lib.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/report_module.o: relocation R_X86_64_32S against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/report_module.o: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -L/home/zzwei/Build_WRF/LIBRARIES/grib2/lib -shared build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_libmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/fortranobject.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/kinds.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/report_module.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/constants.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/gasabs_module.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/rosen98_gasabs.o build/temp.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/mpm93.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/libs/pamgasabs/pamgasabs/pamgasabs_lib/pamgasabs_lib-f2pywrappers2.o -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -lgfortran -o build/lib.linux-x86_64-3.7/pamtra2/libs/pamgasabs/pamgasabs_lib.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1

**Comment by maahn** [comment]
Try to change this line https://github.com/maahn/pamtra2/blob/master/setup.py#L72 to

    ], extra_compile_args = [ "-fPIC"],

If this does not work, please let me know your Linux distribution and version.

By the way, as of now I would still recommend to use the better documented old PAMTRA version: https://github.com/igmk/pamtra. It has also more features.

**Comment by zzwei1** [comment]
> Try to change this line https://github.com/maahn/pamtra2/blob/master/setup.py#L72 to
> 
> ```
> ], extra_compile_args = [ "-fPIC"],
> ```
> 
> If this does not work, please let me know your Linux distribution and version.
> 
> By the way, as of now I would still recommend to use the better documented old PAMTRA version: https://github.com/igmk/pamtra. It has also more features.

Thanks

**Comment by maahn** [comment]
Sorry, I didn't see you had changed your comments, I get an email only when you write a new comment. Regarding the test: It looks like you used an older version of Pamtra2, because all code using `inplace` has been removed in October: 3384e1b90fe1b5b6c32f7aded08fe418fd9800f3

Try to do `git pull`, this will also update the tutorial and the documentation code. The documentation is up-to-date, but the automatic update at readthedocs fails at the moment. Look at the documentation source code in `docs` please.

**Comment by maahn** [comment]
https://pamtra2.readthedocs.io/en/latest/ foxed
